version: 2.1

jobs:
  test:
    parameters:
      golang-version:
        type: string
    docker:
      - image: cimg/go:<< parameters.golang-version >>
    steps:
      - checkout
      - run: make test

workflows:
  test-workflow:
    jobs:
      - test:
          matrix:
            parameters:
              golang-version:
                - '1.13'
                - '1.14'
                - '1.15'
                - '1.16'
                - '1.17'
                - '1.18'
